spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    #    initialization-mode: always
    ## page 글로벌 설정
  #  data :
  #    web :
  #      pageable :
  #        default-page-size: 10
  #        max-page-size : 100
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #          show-sql: true
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true
    defer-datasource-initialization: true
  jackson:
    serialization:
      fail-on-empty-beans: false
#  sql:
#    init:
#      mode: always

#      로그 나오게 하는 것
logging.level:
  org.hibernate.SQL: debug
#  스프링부트 3.0 이상
#  org.hibernate.orm.jdbc.bind: trace

server:
  servlet:
    encoding:
      force-response: true